[package]
name = "yadot"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.82", features = ["backtrace"] }
chumsky = "0.9.3"
clap = "4.5.8"
linked-hash-map = "0.5.6"
yaml-rust = "0.4.5"
