[package]
name = "yadot"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.82", features = ["backtrace"] }
chumsky = "0.9.3"
clap = "4.5.8"
hashlink = "0.8"
saphyr = "0.0.1"
saphyr-parser = "0.0.1"
