[package]
name = "yadot"
version = "0.1.0"
edition = "2021"
build = "src/build.rs"

[build-dependencies]
cfgrammar = "0.13"
lrlex = "0.13"
lrpar = "0.13"

[dependencies]
anyhow = { version = "1.0.82", features = ["backtrace"] }
cfgrammar = "0.13"
lrlex = "0.13"
lrpar = "0.13"
